# global parameters
model_name: textcnn  # 'mlp', 'textcnn'

# dataset parameters
dataset: cr_sents  # 'ag_news', 'dbpedia', 'yelp_review_polarity', 'yelp_review_full', 'yahoo_answers', 'amazon_review_polarity', 'amazon_review_full'
                  # refer to README.md for more info about each dataset
dataset_path: /Users/caiq/Workspace/adp/text-classifier/data/datasets/cr_sents  # folder with dataset
output_path: /Users/caiq/Workspace/adp/text-classifier/data/outputs/cr_sents/sents  # folder with data files saved by preprocess.py

# preprocess parameters
word_limit: 200
min_word_count: 5

# word embeddings parameters
encoder_name:
emb_pretrain: True  # false: initialize embedding weights randomly
                    # true: load pre-trained word embeddings
emb_folder: /Users/caiq/data/vectors/glove.6B  # only makes sense when `emb_pretrain: True`
emb_filename: glove.6B.50d.txt  # only makes sense when `emb_pretrain: True`
emb_size: 256  # word embedding size
               # only makes sense when `emb_pretrain: False`
fine_tune_word_embeddings: True  # fine-tune word embeddings?

# model parameters
conv_layer: '1D' # '1D', '2D', use 1D or 2D convolution layer
n_kernels: 100
kernel_sizes: [3, 4, 5]
n_channels: 2
dropout: 0.3  # dropout

# checkpoint saving parameters
checkpoint_path: /Users/caiq/Workspace/third-party/Text-Classification/models/cr_sents/CNN/checkpoints  # path to save checkpoints, null if never save checkpoints
checkpoint_basename: checkpoint_textcnn_crsents  # basename of the checkpoint

# training parameters
start_epoch: 0  # start at this epoch
batch_size: 64  # batch size
lr: 0.001  # learning rate
lr_decay: 0.3  # a factor to multiply learning rate with (0, 1)
workers: 4  # number of workers for loading data in the DataLoader
num_epochs: 5  # number of epochs to run
grad_clip: null  # clip gradients at this value, null if never clip gradients
print_freq: 2  # print training status every __ batches
checkpoint: null  # path to model checkpoint, null if none
# tensorboard
tensorboard: True  # enable tensorboard or not?
log_dir: /Users/caiq/Workspace/adp/text-classifier/data/logs/cr_sents/CNN/fasttext # folder to save logs for tensorboard, only makes sense when `tensorboard: True`
