# global parameters
model_name: mlp  # 'mlp', 'textcnn'

# dataset parameters
dataset: imdb  # e.g. 'ag_news', 'imdb'
dataset_path: /Users/caiq/Workspace/adp/text-classifier/data/datasets/sentiment/aclImdb/grouped  # folder with dataset
output_path: /Users/caiq/Workspace/adp/text-classifier/data/outputs/imdb/sents  # folder with data files saved by preprocess.py

# preprocess parameters
word_limit: 200
min_word_count: 5

# word embeddings parameters
encoder_name:
emb_pretrain: True  # false: initialize embedding weights randomly
                    # true: load pre-trained word embeddings
emb_folder: /Users/caiq/data/vectors/glove.6B  # only makes sense when `emb_pretrain: True`
emb_filename: glove.6B.100d.txt  # only makes sense when `emb_pretrain: True`
emb_size: 256  # word embedding size
               # only makes sense when `emb_pretrain: False`
fine_tune_word_embeddings: True  # fine-tune word embeddings?

# model parameters
hidden_size: 10

# checkpoint saving parameters
checkpoint_path: /Users/caiq/Workspace/adp/text-classifier/data/models/imdb/MLP/checkpoints  # path to save checkpoints, null if never save checkpoints
checkpoint_basename: checkpoint_textmlp_imdb  # basename of the checkpoint

# training parameters
start_epoch: 0  # start at this epoch
batch_size: 64  # batch size
lr: 0.001  # learning rate
lr_decay: 0.9  # a factor to multiply learning rate with (0, 1)
workers: 4  # number of workers for loading data in the DataLoader
num_epochs: 10  # number of epochs to run
grad_clip: null  # clip gradients at this value, null if never clip gradients
print_freq: 100  # print training status every __ batches
checkpoint: null  # path to model checkpoint, null if none
# tensorboard
tensorboard: True  # enable tensorboard or not?
log_dir: /Users/caiq/Workspace/adp/text-classifier/data/logs/imdb/MLP/fasttext # folder to save logs for tensorboard, only makes sense when `tensorboard: True`